# Generated by Django 2.2.9 on 2020-03-17 15:58

import api.models
import api.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0042_auto_20200128_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformalUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('situational_overview', models.TextField(blank=True, null=True)),
                ('focal_point_originator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('focal_point_originator_email', models.CharField(blank=True, max_length=200, null=True)),
                ('focal_point_originator_job', models.CharField(blank=True, max_length=200, null=True)),
                ('focal_point_originator_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('focal_point_ifrc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('focal_point_ifrc_email', models.CharField(blank=True, max_length=300, null=True)),
                ('focal_point_ifrc_job', models.CharField(blank=True, max_length=200, null=True)),
                ('focal_point_ifrc_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('graphic', models.FileField(blank=True, null=True, storage=api.storage.AzureStorage(), upload_to=api.models.informal_update_graphic_path)),
                ('countries', models.ManyToManyField(to='api.Country')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event')),
                ('regions', models.ManyToManyField(to='api.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformalUpdateReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc_date', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, storage=api.storage.AzureStorage(), upload_to=api.models.informal_update_document_path)),
                ('document_url', models.URLField(blank=True)),
                ('informal_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InformalUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='InformalUpdateActionsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('NTLS', 'National Society'), ('PNS', 'Foreign Society'), ('FDRN', 'Federation')], max_length=4)),
                ('summary', models.TextField(blank=True)),
                ('actions', models.ManyToManyField(to='api.Action')),
                ('informal_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informal_update_actions_taken', to='api.InformalUpdate')),
            ],
        ),
    ]
