# Generated by Django 2.2.9 on 2020-03-17 16:36

import api.models
import api.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_informalupdate_informalupdateactionstaken_informalupdatereference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informalupdate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_update', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='informalupdate',
            name='graphic',
            field=models.ImageField(blank=True, null=True, storage=api.storage.AzureStorage(), upload_to=api.models.informal_update_graphic_path),
        ),
        migrations.AlterField(
            model_name='informalupdatereference',
            name='informal_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informal_update_references', to='api.InformalUpdate'),
        ),
    ]
