# Generated by Django 2.2.13 on 2020-07-16 16:46

import deployments.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0031_auto_20200701_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.IntegerField(default=-1, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiary_type',
            field=models.IntegerField(default=-1, verbose_name='beneficiary type'),
        ),
        migrations.AddField(
            model_name='project',
            name='organizational_unit',
            field=enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.OrganizationalUnits, verbose_name='organizational unit'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner',
            field=enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.Partners, verbose_name='partner'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_00_05',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 00 05'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_06_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 06 12'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 13 17'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 18 29'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 30 39'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 40 49'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 50 59'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 60 69'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 70 79'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female_80_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female 80 plus'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached LGBTIQ'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_00_05',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 00 05'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_06_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 06 12'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 13 17'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 18 29'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 30 39'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 40 49'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 50 59'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 60 69'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 70 79'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_lgbtiq_80_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached lgbtiq 80 plus'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_00_05',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 00 05'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_06_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 06 12'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 13 17'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 18 29'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 30 39'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 40 49'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 50 59'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 60 69'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 70 79'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male_80_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male 80 plus'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_people_with_disability',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached people with disability'),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_pregnant_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached pregnant women'),
        ),
        migrations.AddField(
            model_name='project',
            name='subactivity',
            field=models.IntegerField(default=-1, verbose_name='subactivity'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_00_05',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 00 05'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_06_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 06 12'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 13 17'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 18 29'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 30 39'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 40 49'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 50 59'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 60 69'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 70 79'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female_80_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female 80 plus'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq',
            field=models.IntegerField(blank=True, null=True, verbose_name='target LGBTIQ'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_00_05',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 00 05'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_06_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 06 12'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 13 17'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 18 29'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 30 39'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 40 49'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 50 59'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 60 69'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 70 79'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_lgbtiq_80_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='target lgbtiq 80 plus'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_00_05',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 00 05'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_06_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 06 12'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 13 17'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 18 29'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 30 39'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 40 49'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 50 59'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 60 69'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 70 79'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male_80_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male 80 plus'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_people_with_disability',
            field=models.IntegerField(blank=True, null=True, verbose_name='target people with disability'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_pregnant_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='target pregnant women'),
        ),
        migrations.AddField(
            model_name='project',
            name='units_measurement_metric',
            field=models.IntegerField(default=-1, verbose_name='units measurement metric'),
        ),
        migrations.AddField(
            model_name='project',
            name='units_quantity',
            field=models.IntegerField(default=-1, verbose_name='units quantity'),
        ),
        migrations.AddField(
            model_name='project',
            name='where_delivery_service_name',
            field=models.TextField(blank=True, null=True, verbose_name='where delivery service name'),
        ),
        migrations.AddField(
            model_name='project',
            name='where_delivery_service_place',
            field=models.IntegerField(default=-1, verbose_name='where delivery service place'),
        ),
        migrations.AddField(
            model_name='project',
            name='where_district',
            field=models.IntegerField(default=-1, verbose_name='where district'),
        ),
        migrations.AddField(
            model_name='project',
            name='where_municipality',
            field=models.IntegerField(default=-1, verbose_name='where municipality'),
        ),
        migrations.AddField(
            model_name='project',
            name='where_province',
            field=models.IntegerField(default=-1, verbose_name='where province'),
        ),
        migrations.AddField(
            model_name='project',
            name='where_ward',
            field=models.IntegerField(default=-1, verbose_name='where ward'),
        ),
    ]
