# Generated by Django 2.2.13 on 2020-07-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0032_auto_20200716_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='where_municipality',
            field=models.IntegerField(blank=True, null=True, verbose_name='where municipality'),
        ),
        migrations.AlterField(
            model_name='project',
            name='where_ward',
            field=models.IntegerField(blank=True, null=True, verbose_name='where ward'),
        ),
    ]
