# Generated by Django 2.2.13 on 2020-07-17 23:16

import deployments.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0034_auto_20200717_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='where_municipality',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=deployments.models.Municipalities, null=True, verbose_name='where municipality'),
        ),
    ]
